### ISSUE TITLE
does Navis EBR exist?

### ISSUE THREAD

**Issue by elsteffen** [nvs-vocabs/R08#5]
I cannot see a Navis EBR float.  Navis A (instrument 863) floats have a different configuration of their buoyancy system than Navis EBR .  Since that conversion happened in 2015, I am concerned I am somehow missing an entry in the table.

**Comment by tcarval** [comment]
Hello @elsteffen,
When I look in the file format checker reference files, I see that we have an entry for NAVIS_EBR in table R23, but no entry in table R08. That does not prevent 1021 Navis EBR floats to be available on GDAC.

ref_table-23:NAVIS_EBR | 501 | 869 | SBE | SBE FLoat. serial >=590  |
ref_table-23:NAVIS_A | 500 | 863 | SBE | SBE Float |
ref_table-8:863 | Navis-A Float

Should I add an entry for NAVIS_EBR in reference table 8 ?

**Comment by elsteffen** [comment]
Hello

   Sorry, I don't understand the distinctions between the
reference tables.  I have been researching what WMO instrument number we
should be using for our floats and realized I couldn't find Navis EBR.
   We definitely want to be able to use some designation for EBR.  Is 869
it, or is there another step before it is available for use?

thank you

**Comment by tcarval** [comment]
Hello @vturpin 
The NAVIS_EBR Argo float is not registered in WMO "Common Code Tables C-3 (CCT C-3).
Can you add the entry:
<html>
<body>


CodeFigureForIXIIXIX | CodeFigureForBUFR | InstrumentMakeAndType_en | EquationCoefficients_a | EquationCoefficients_b | Status
-- | -- | -- | -- | -- | --
869 | 869 | NAVIS_EBR, SBE conductivity sensor, float serial number >=590  |   |   | Operational




</body>
</html>

**Comment by vturpin** [comment]
Addition submitted here: https://github.com/wmo-im/CCT/issues/128

**Comment by vpaba** [comment]
Thanks for requesting this new addition to WMO. The next step is to mirror this update on R08 - happy to help with this!

**Comment by vturpin** [comment]
This is in progress. No objection from the group.
Should be addopted for next release of the CCT.
see https://github.com/wmo-im/CCT/issues/128 and https://github.com/wmo-im/CCT/issues/115

**Comment by vturpin** [comment]
New id: 869 "NAVIS_EBR, SBE conductivity sensor"

**Comment by tcarval** [comment]
We can close this ticket.
On WMO side, NAVIS_EBR is managed in this ticket : https://github.com/wmo-im/CCT/issues/128#issuecomment-1578672187

**Comment by SBS-EREHM** [comment]
I have asked again wmo-im to populate id 869.   with NAVIS_EBR.

See https://github.com/wmo-im/CCT/issues/128#issuecomment-1800745337
